lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item_to_list, name='add_item_to_list'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
]

lists/models.py
from django.db import models

class List(models.Model):
    pass

# Create your models here.
class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List

# Create your views here.
def home_page(req):
    return render(req, 'home.html')

def view_list(req, list_id):
    list_ = List.objects.get(id=list_id)
    items = Item.objects.filter(list=list_)
    #return render(req, 'list.html', {'items': items })
    return render(req, 'list.html', {'list': list_ })

def add_item_to_list(req, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=req.POST.get('item_text', ''), list=list_)
    return redirect(f'/lists/{list_.id}/')

def new_list(req):
    list_ = List.objects.create()
    Item.objects.create(text=req.POST.get('item_text', ''), list=list_)
    return redirect(f'/lists/{list_.id}/')

lists/templates/home.html
<html>
  <head>
    <title>Start a new To-Do list</title>
    <form method="POST" action="/lists/new">
      <input id='id_new_item' name='item_text' placeholder="Enter a to-do item" />
      {% csrf_token %}
    </form>
  </head>
</html>

lists/templates/list.html
<html>
  <head>
    <title>To-Do lists</title>
    <form method="POST" action="/lists/{{ list.id }}/add_item">
      <input id='id_new_item' name='item_text' placeholder="Enter a to-do item" />
      {% csrf_token %}
    </form>
    <table id="id_list_table">
      {% for item in list.item_set.all %}
        <tr><td>{{ forloop.counter }}: {{ item.text }}</td><tr>
	    {% endfor %}
    </table>
  </head>
  <body>
    <h1>Your To-Do list</h1>
  </body>
</html>